# Generated by Django 5.0.3 on 2024-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.CharField(default='no tag', max_length=255),
        ),
    ]
